import Head from "next/head";
import Image from "next/image";
import { Container, Row, Col } from "react-bootstrap";
import styles from "@/styles/Home.module.scss";

import TextoImagenCTA from "@/components/Main/TextoImagenCTA/TextoImagenCTA";
import PricingCard from "@/components/Main/PricingCard/PricingCard";

import HeroText from "@/components/Main/HeroText/HeroText";
import { Main } from "next/document";
import MainFeatures from "@/components/Main/MainFeatures/MainFeatures";
import HeroVideo from "@/components/Main/HeroVideo/HeroVideo";
import Testimonial from "@/components/Main/Testimonial/Testimonial";
import FaqQuestions from "@/components/Main/FaqQuestions/FaqQuestions";
import ContactForm from "@/components/Main/ContactForm/ContactForm";
import GoogleContactForm from "@/components/Main/GoogleContactForm/GoogleContactForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>AnvetCard</title>
        <meta name="description" content="Generated by Anvetcorp" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section id="Home" className={styles.heroSection}>
          <Row>
            <Col>
              <HeroText />
            </Col>
          </Row>
        </section>

        <section className={styles.mainFeatures}>
          <Row>
            <Col>
              <MainFeatures />
            </Col>
          </Row>
        </section>

        <section id="About" className={styles.heroVideo}>
          <Row>
            <Col className={styles.videoContainer}>
              <HeroVideo
                title="Conoce a AnvetCard"
                description="Descubre el poder de AnvetCard y lleva tu red profesional al siguiente nivel."
                src="/videos/video2.mp4"
              />
            </Col>
            <Col className={styles.videoContainer}>
              <HeroVideo
                title="Interación en un clic"
                description="Fácil de compartir, fácil de usar. Con AnvetCard, tu red profesional está a un clic de distancia."
                src="/videos/anvetcard1.mp4"
              />
            </Col>
          </Row>
        </section>

        <section id="Features" className={styles.featuresSection}>
          <Row className={styles.feature1}>
            <Col className={styles.colFeature1}>
              <TextoImagenCTA
                ladoTexto="izquierda"
                titulo="Innovación al Alcance de Tu Mano"
                texto="AnvetCard transforma tu red profesional permitiéndote compartir tu perfil con un clic. Elimina las tarjetas físicas y asegura que tu información siempre esté actualizada y accesible."
                imageUrl="/images/components/features_left.png"
                ctaUrl="Pricing"
                ctaTexto="Descubre Nuestros Planes"
                caracteristicas={{
                  columna1: ["Diseño personalizable", "Fácil Compartir", "Interacción en un clic"],
                  columna2: ["Integración de redes sociales", "Eco-Amigable", "Seguridad de datos"],
                }}
              />
            </Col>
          </Row>
          <Row className={styles.feature2}>
            <Col className={styles.colFeature2}>
              <TextoImagenCTA
                ladoTexto="derecha"
                titulo="Maximiza Tu Impacto"
                // texto="Explora las ventajas únicas de AnvetCard."
                imageUrl="/images/components/features_right.jpg"
                ctaUrl="Contact"
                ctaTexto="Contáctanos"
                titulosConDescripcion={[
                  {
                    subtitulo: "Costo-Efectividad",
                    descripcion:
                      "Olvídate de reimprimir tarjetas por cada cambio de información. Con AnvetCard, las actualizaciones son inmediatas, asegurando que tu red siempre tenga acceso a tus datos más recientes.",
                  },
                  {
                    subtitulo: "Expansión Global",
                    descripcion:
                      "Lleva tu red profesional a una escala global. AnvetCard trasciende barreras geográficas, permitiendo compartir tu perfil profesional con cualquier persona, en cualquier lugar.",
                  },
                  {
                    subtitulo: "Confianza y Credibilidad",
                    descripcion:
                      "Construye confianza instantáneamente. AnvetCard te permite presentar una imagen profesional coherente y verificada, fortaleciendo tu credibilidad en el ámbito digital.",
                  },
                ]}
              />
            </Col>
          </Row>
        </section>

        <section id="Testimonios" className={styles.testimonialSection}>
          <Testimonial />
        </section>

        <section id="Pricing" className={styles.pricingSection}>
          <h2 className={styles.pricingTitle}>Elige Tu Camino Digital</h2>
          <p className={styles.pricingDescription}>
            No hay dos profesionales iguales, y tu tarjeta digital debería reflejar eso. Con
            AnvetCard, tienes el poder de personalizar tu presencia en línea con planes que van
            desde lo esencial hasta lo excepcional. Ya sea que busques hacer una primera impresión
            memorable o gestionar conexiones a gran escala, nuestros planes están diseñados para
            ayudarte a lograr tus objetivos con estilo y eficacia
          </p>
          <Row className={styles.pricingCards}>
            <Col md={4} sm={12}>
              <PricingCard
                planName="Starter"
                price={40}
                period="Anual"
                features={[
                  "Foto de perfil",
                  "Enlaces a redes sociales (hasta 4)",
                  "Iconos de contacto",
                  "Galería o carrusel de imágenes (Hasta 4 imágenes)",
                  "Video / Código QR / Imagen destacada (2 imágenes)",
                ]}
                buttonText="Comprar"
                buttonAction={() => {
                  alert("Comprando el plan premium");
                }}
              />
            </Col>
            <Col md={4} sm={12}>
              <PricingCard
                planName="Profesional"
                price={50}
                period="Anual"
                features={[
                  "Foto de perfil",
                  "Enlaces a redes sociales (hasta 6)",
                  "Iconos de contacto",
                  "Galería o carrusel de imágenes (hasta 5 imágenes)",
                  "Componente de educación y certificaciones",
                  "Componente de experiencia laboral / Servicios",
                  "Productos destacados / Video / QR Code",
                  "Componente de métodos de pago",
                ]}
                buttonText="Comprar"
                buttonAction={() => {
                  alert("Comprando el plan básico");
                }}
              />
            </Col>
            <Col md={4} sm={12}>
              <PricingCard
                planName="Elite"
                price={60}
                period="Anual"
                features={[
                  "Foto de perfil",
                  "Enlaces a redes sociales (Ilimitadas)",
                  "Iconos de contacto",
                  "Galería o carrusel de imágenes (ilimitadas)",
                  "Componente de educación y certificaciones",
                  "Componente de experiencia laboral",
                  "Componente de Servicios",
                  "Componente de Productos destacados",
                  "Video (4 videos)",
                  "QR Code",
                  "Componente de métodos de pago",
                ]}
                buttonText="Comprar"
                buttonAction={() => {
                  alert("Comprando el plan premium");
                }}
              />
            </Col>
          </Row>
          <div className={styles.separator}></div>
          <h2 className={styles.Promociones}>Renueva a Mitad de Precio</h2>
          <h2 className={styles.Promociones}>Oferta Exclusiva para Pioneros Digitales</h2>
          <p className={styles.pricingDescription}>
            En AnvetCard, valoramos a quienes se adelantan al futuro. Por eso, las primeras 100
            personas que se unan a nuestra revolución digital no solo disfrutarán de las ventajas de
            ser pioneros, sino que también recibirán un 50% de descuento en su renovación. Esta es
            tu oportunidad de mantener tu presencia digital al más alto nivel con una oferta
            inigualable. Sé rápido, sé uno de los primeros, y asegura tu futuro digital a mitad de
            precio.
          </p>
        </section>

        <section id="FAQ" className={styles.faqSection}>
          <FaqQuestions />
        </section>

        {/* <section id="Contacto" className={styles.contactSection}>
          <Row>
            <Col>
              <ContactForm />
            </Col>
          </Row>
        </section> */}

        <section id="Contacto" className={styles.contactSection}>
          <Row>
            <Col>
              <GoogleContactForm />
            </Col>
          </Row>
        </section>
      </main>
    </>
  );
}
